### ISSUE TITLE
Bug: Twitter app error

### ISSUE THREAD

**Issue by ultrahacx** [project-error/new-phone-who-dis#82] opened 2021-02-09 11:37 UTC
**Describe the bug**
When I try to setup a Twitter account (Profile Name), phone throws an `Uncaught TypeError: e.onClick is not a function`. Weird thing which I noticed is when I first launched the Twitter app, it opened Twitter homepage(idk exactly what it is, but it seemed like phone was trying to load tweets) but then the Twitter app closed. On relaunching the app, I got the Twitter account setup with `Profile Name` field

**To Reproduce**
1. Open phone
2. Open Twitter app
3. Enter a username and click the button

**Expected behavior**
Successful creation of Twitter account was expected

**Evidence**
https://cdn.discordapp.com/attachments/791854455468458040/808651122465308672/unknown.png
https://cdn.discordapp.com/attachments/791854455468458040/808651178052812800/unknown.png

**Needed information (please complete the following information):**
 - **Server OS**: Windows 10
- **Server Artifact version**: v1.0.0.2941
- What version of **new-phone-who-dis** are you running?: IDK but I fresh built the master branch today (Feb 9,2021)

**Comment by TasoOneAsia** [comment] 2021-02-09 14:30
Would you be able to also to grab a screenshot of the `nui_devTools` console logs as well, I have your errors in Sentry but won't do much good until #81 is merged, allowing for better source maps. Only asking cause you might be able to grab them faster than I can atm :)

**Comment by ultrahacx** [comment] 2021-02-09 14:47
Yeah sure. Here's the screenshot of loading Twitter homepage which I mentioned earlier:
![image](https://user-images.githubusercontent.com/43913907/107379595-17a25f80-6b13-11eb-9691-8bcd14b7496e.png)
And if I click anything on phone, the phone crashes with the following error and Im unable to open the phone UI again unless I restart the resource:
![image](https://user-images.githubusercontent.com/43913907/107379835-53d5c000-6b13-11eb-9260-36af9c7118da.png)

After the resource restart I get the Twitter account setup screen like this:
![image](https://user-images.githubusercontent.com/43913907/107380099-94353e00-6b13-11eb-926b-c4926953a200.png)
And now if I enter the username and try to proceed forward I can't. Here's the devtools screenshot after entering username and clicking the button
![image](https://user-images.githubusercontent.com/43913907/107380281-bf1f9200-6b13-11eb-9015-33c9279f4694.png)

**Comment by TasoOneAsia** [comment] 2021-02-09 16:21
@ultrahacx Looks like database returns aren't being nice to you, Discord will probably be the best way to look about. 👍

**Comment by RockySouthpaw** [comment] 2021-02-09 16:27
I’ll try latest master branch sometime today and see if I can repro.

**Comment by RockySouthpaw** [comment] 2021-02-10 06:43
Looks like the issue is related to kash. Resource doesn't seem compatible with it for whatever reason. We've tested the phone on numerous artifact versions as well as esx 1.1/esx 1.2 without experiencing this issue. 

I made sure to include this in the `server/main.lua`
```
local IdentifierTables = {
    {table = "users", column = "identifier"},
    {table = "npwd_calls", column = "identifier"},
    {table = "npwd_notes", column = "identifier"},
    {table = "npwd_phone_contacts", column = "identifier"},
    {table = "npwd_phone_gallery", column = "identifier"},
    {table = "npwd_sellout_listings", column = "identifier"},
    {table = "npwd_twitter_profiles", column = "identifier"},
    {table = "npwd_twitter_tweets", column = "identifier"}
}
```

i changed the identifier columns from 40 to 48 and still doesn't work🤷🏻. We can look into this issue again when its released, but for now the issue is going to be closed and will be tracked on the gitkraken [here](https://app.gitkraken.com/glo/card/e593ef208c0d42b08dd771917e39a9c6)

**Closed by RockySouthpaw** 2021-02-10 06:43 UTC
Labels: New Issue, Tracked Issue
